package com.taskflow.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Task Model — The Data Structure
 * =================================
 *
 * WHAT DOES THIS FILE DO?
 * This defines the shape of our data — like a Mongoose Schema in Node.js.
 * Each Task object maps to a document in the MongoDB "tasks" collection.
 *
 * WHAT IS @Document?
 * It tells Spring: "This class represents a MongoDB document."
 * The 'collection' parameter specifies which MongoDB collection to use.
 *
 * WHAT IS @Id?
 * It marks the 'id' field as the primary key.
 * MongoDB auto-generates a unique ID (like ObjectId in Mongoose).
 *
 * EXAMPLE DOCUMENT IN MONGODB:
 * {
 *   "_id": "664a1b2c3d4e5f6789012345",
 *   "title": "Learn Spring Boot",
 *   "completed": false
 * }
 */
@Document(collection = "tasks")  // Maps this class to the "tasks" collection in MongoDB
public class Task {

    @Id  // This field is the unique identifier (auto-generated by MongoDB)
    private String id;

    private String title;       // The task description (e.g., "Buy groceries")
    private boolean completed;  // Task status: true = done, false = pending

    // ==========================================
    // CONSTRUCTORS
    // ==========================================

    /**
     * Default constructor — Required by Spring Data MongoDB.
     * Spring needs this to create Task objects from database documents.
     */
    public Task() {
    }

    /**
     * Parameterized constructor — For creating new tasks easily.
     * We don't pass 'id' because MongoDB generates it automatically.
     */
    public Task(String title, boolean completed) {
        this.title = title;
        this.completed = completed;
    }

    // ==========================================
    // GETTERS AND SETTERS
    // ==========================================
    // These are like object properties in JavaScript.
    // Java uses getter/setter methods to access private fields.
    // Why? It's called "Encapsulation" — a core OOP concept.
    // We keep fields private and provide controlled access.

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    // ==========================================
    // toString() — For debugging/logging
    // ==========================================
    @Override
    public String toString() {
        return "Task{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", completed=" + completed +
                '}';
    }
}
